#!/bin/sh -e

./configure \
    --prefix=/usr \
    --disable-gtk-doc \
    --disable-http2 \
    --disable-man \
    --disable-rofiles-fuse \
    --without-soup \
    --with-curl

make
make DESTDIR="$1" install
