#!/bin/sh -e

for file in patches/* ; do
	patch -p1 < "$file"
done

./configure \
    --prefix=/usr \
    --disable-gtk-doc \
    --disable-http2 \
    --disable-man \
    --disable-rofiles-fuse \
    --without-soup \
    --with-curl

make
make DESTDIR="$1" install
