#!/usr/bin/env sh

cd "AppStream-$2"

for file in ../patches/* ; do
	patch -p1 < "$file"
done

# Don't build the docs and languages, which pull in a lot of dependencies.
sed -e "s/^subdir('po\/')/#subdir('po\/')/" \
	-e "s/^subdir('docs\/')/#subdir('docs\/')/" meson.build > _
mv -f _ meson.build

mkdir build
cd build

meson \
    --prefix=/usr \
    --sysconfdir=/etc \
    --localstatedir=/var \
    -Dqt=false \
    -Dmaintainer=false \
    -Ddocs=false \
    -Dapidocs=false \
    -Dinstall-docs=false \
    -Dstemming=false \
    -Dvapi=false \
    -Dapt-support=false \
    -Dgir=false \
    -Dlibxmlb:introspection=false \
    ..

ninja
ninja install
