#!/usr/bin/env sh

cd AppStream-0.15.4

mkdir build
cd build

meson \
    --prefix=/usr \
    --sysconfdir=/etc \
    --localstatedir=/var \
    -Dqt=false \
    -Dmaintainer=false \
    -Ddocs=false \
    -Dapidocs=false \
    -Dinstall-docs=false \
    -Dstemming=false \
    -Dvapi=false \
    -Dapt-support=false \
    -Dgir=false \
    ..

ninja
ninja install
