#!/usr/bin/env sh

cd "AppStream-$2"

for file in ../patches/* ; do
	patch -p1 < "$file"
done

mkdir build
cd build

meson \
    --prefix=/usr \
    --sysconfdir=/etc \
    --localstatedir=/var \
    -Dqt=false \
    -Dmaintainer=false \
    -Ddocs=false \
    -Dapidocs=false \
    -Dinstall-docs=false \
    -Dstemming=false \
    -Dvapi=false \
    -Dapt-support=false \
    -Dgir=false \
    ..

ninja
ninja install
